# Generated by Django 2.1.5 on 2019-04-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20190330_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='result',
            field=models.TextField(blank=True, default='initialized', max_length=256, null=True),
        ),
    ]
