# Generated by Django 2.1.5 on 2019-04-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20190402_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.CharField(max_length=256),
        ),
    ]
